"""
prepare_data.py — one-time script to generate quotes_data.star
Run: python3 prepare_data.py
"""
import csv
import re
import urllib.request
from collections import defaultdict

URL = "https://raw.githubusercontent.com/JohannesNE/literature-clock/master/litclock_annotated.csv"
OUTPUT = "app/author_clock.star"
CONTEXT_LEN = 50

def strip_html(text):
    text = re.sub(r"<[^>]+>", "", text)
    text = text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
    text = text.replace("&nbsp;", " ").replace("&quot;", '"').replace("&#39;", "'")
    text = text.replace("&rsquo;", "'").replace("&lsquo;", "'")
    text = text.replace("&rdquo;", '"').replace("&ldquo;", '"')
    text = text.replace("&mdash;", "—").replace("&ndash;", "–")
    text = text.replace("&hellip;", "…")
    return text.strip()

def escape_starlark(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    # Escape non-ASCII as \uXXXX so the .star file is pure ASCII
    result = []
    for c in s:
        if ord(c) > 127:
            result.append("\\u%04x" % ord(c))
        else:
            result.append(c)
    return "".join(result)

def main():
    print(f"Downloading CSV from {URL} ...")
    with urllib.request.urlopen(URL) as resp:
        raw = resp.read().decode("utf-8")

    print("Parsing rows ...")
    reader = csv.reader(raw.splitlines(), delimiter="|")

    quotes = defaultdict(list)
    skipped_sfw = 0
    skipped_notfound = 0
    total = 0

    for row in reader:
        if len(row) < 6:
            continue
        time_str = row[0].strip()
        time_case = strip_html(row[1].strip())
        full_quote = strip_html(row[2].strip())
        # title = row[3].strip()  # not stored — saves space
        author = strip_html(row[4].strip())
        sfw = row[5].strip()

        total += 1

        if sfw == "nsfw":
            skipped_sfw += 1
            continue

        # Validate time format HH:MM
        if not re.match(r"^\d{2}:\d{2}$", time_str):
            continue

        # Find time_case in full_quote (case-sensitive first, then case-insensitive)
        idx = full_quote.find(time_case)
        if idx == -1:
            idx = full_quote.lower().find(time_case.lower())
        if idx == -1:
            skipped_notfound += 1
            continue

        before = full_quote[:idx]
        after = full_quote[idx + len(time_case):]

        # Truncate: last 50 chars of before, first 50 chars of after
        before = before[-CONTEXT_LEN:].lstrip()
        after = after[:CONTEXT_LEN].rstrip()

        key = time_str.replace(":", "_")
        quotes[key].append({
            "b": before,
            "t": time_case,
            "a": after,
            "au": author,
        })

    print(f"Total rows: {total}")
    print(f"Skipped (not sfw): {skipped_sfw}")
    print(f"Skipped (time phrase not found): {skipped_notfound}")
    print(f"Keys (minutes): {len(quotes)}")
    print(f"Total quotes kept: {sum(len(v) for v in quotes.values())}")

    print(f"Writing {OUTPUT} ...")

    # Build QUOTES dict block
    data_lines = ["# AUTO-GENERATED by prepare_data.py - do not edit manually", "QUOTES = {"]
    for key in sorted(quotes.keys()):
        entries = quotes[key]
        data_lines.append(f'    "{key}": [')
        for e in entries:
            b = escape_starlark(e["b"])
            t = escape_starlark(e["t"])
            a = escape_starlark(e["a"])
            au = escape_starlark(e["au"])
            data_lines.append(f'        {{"b": "{b}", "t": "{t}", "a": "{a}", "au": "{au}"}},')
        data_lines.append("    ],")
    data_lines.append("}")

    app_logic = '''
load("render.star", "render")
load("time.star", "time")

DEFAULT_TZ = "America/New_York"

def _pad(n):
    if n < 10:
        return "0" + str(n)
    return str(n)

def main(config):
    tz = config.get("timezone", DEFAULT_TZ)

    now = time.now().in_location(tz)

    hour = now.hour
    minute = now.minute
    key = _pad(hour) + "_" + _pad(minute)

    entries = QUOTES.get(key, [])

    if len(entries) == 0:
        return render.Root(
            child = render.Box(
                width = 64,
                height = 32,
                child = render.Text(
                    content = str(hour) + ":" + _pad(minute),
                    font = "CG-pixel-3x5-mono",
                    color = "#FFD700",
                ),
            ),
        )

    entry = entries[0]
    before = entry["b"]
    time_case = entry["t"]
    after = entry["a"]
    author = entry["au"]

    quote_children = []

    if len(before) > 0:
        quote_children.append(
            render.WrappedText(
                content = before,
                font = "CG-pixel-3x5-mono",
                color = "#ffffff",
                width = 64,
                linespacing = 2,
            ),
        )
        quote_children.append(render.Box(width=64, height=6, color="#000000"))

    quote_children.append(
        render.WrappedText(
            content = time_case,
            font = "CG-pixel-3x5-mono",
            color = "#FFD700",
            width = 64,
            linespacing = 2,
        ),
    )

    if len(after) > 0:
        quote_children.append(render.Box(width=64, height=6, color="#000000"))
        quote_children.append(
            render.WrappedText(
                content = after,
                font = "CG-pixel-3x5-mono",
                color = "#aaaaaa",
                width = 64,
                linespacing = 2,
            ),
        )

    return render.Root(
        delay = 150,
        child = render.Column(
            children = [
                render.Marquee(
                    scroll_direction = "vertical",
                    height = 25,
                    child = render.Column(
                        children = quote_children,
                    ),
                ),
                render.Box(
                    width = 64,
                    height = 1,
                    color = "#333333",
                ),
                render.Marquee(
                    scroll_direction = "horizontal",
                    width = 64,
                    child = render.Text(
                        content = "\\u2014 " + author,
                        font = "CG-pixel-3x5-mono",
                        color = "#888888",
                    ),
                ),
            ],
        ),
    )
'''

    import os
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="ascii") as f:
        f.write("\n".join(data_lines))
        f.write("\n")
        f.write(app_logic)

    size_kb = os.path.getsize(OUTPUT) / 1024
    print(f"Done! {OUTPUT} is {size_kb:.0f} KB")

if __name__ == "__main__":
    main()
